# Generated by Django 4.2.3 on 2023-07-09 08:14

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('image', models.ImageField(upload_to='static/image-product')),
                ('description', djrichtextfield.models.RichTextField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(null=True)),
                ('activate', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
